### ISSUE TITLE
No clean way to close app on OSX

### ISSUE THREAD

**Issue by mk-rocket** [gurayyarar/SnipCommand#5]
The only option is to close the current window. CMD+Q does not quit the app.

**Comment by Saif807380** [comment]
Can I work on this?

**Comment by kant** [comment]
When I close the main window, when I click in Preferences it gives me this message: 
```
A javascript error ocurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at click (/Applications/SnipCommand.app/Contents/Resources/app.asar/build/menu.js:11:53)
    at MenuItem.click (electron/js2c/browser_init.js:65:1624)
    at Function.executeCommand (electron/js2c/browser_init.js:73:1102)
```
The only way of Quit is `Force Quit` --> `Force quit applications`
